name: End-to-end tests

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ["18.x"]
        os: [ubuntu-latest]

    env:
      NEXT_PUBLIC_API_BASE: https://dinar-staging.dhaif.io/api
      NEXT_PUBLIC_API_BASE_V2: https://dinar-staging.dhaif.io/v2

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Install deps (with cache)
        run: yarn install

      - name: build
        run: yarn build

      - name: Run e2e tests
        run: yarn run test:e2e
